### ISSUE TITLE
Always on aiming

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Offbot_Code#109]
When we have a note, the robot should always be aiming at the speaker (default to prep vision after collection)

Controllers should rumble when shooting ready so driver knows to stop moving and operator knows to shoot.

(We could even get fancy and have operator stick not vibrate until DT is not moving, or do auto shooting or shoot on the fly)

**Comment by alicekuznetsov** [comment]
No on that first one- it would definitely mess with kevins head too much, and the shooter would pivot up. We can already queue it before intaking and i think that's enough 
The rumble is sick though. I agree with that
