### ISSUE TITLE
Game piece in robot detection (not fully collected just entered robot)

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Offbot_Code#118]
beam break at the start of intake

**Comment by alicekuznetsov** [comment]
Do we want any logic surrounding this? Do we just want to add controller rumble for now? I think we need to have a discussion about how we want to use this sensor logically, but I'm leaning towards it solely being a driver feedback thing right now

**Comment by ACat701** [comment]
Fuaohahaovaigaoaauaflbablabkabl

**Comment by TaylerUva** [comment]
> Do we want any logic surrounding this? Do we just want to add controller rumble for now? I think we need to have a discussion about how we want to use this sensor logically, but I'm leaning towards it solely being a driver feedback thing right now

I vote just driver feedback

**Comment by alicekuznetsov** [comment]
Yarrg i agree
I think the 118 style note ejecting is a very last last thing

**Comment by alicekuznetsov** [comment]
Still needs:
- Add LED pattern when the beam break sensor is activated (This will make it a short flash, which is fine since I would have asked for a short flash anyway)
- Add a short controller rumble to both controllers that is distinct enough from the Game Piece Collected rumble
