### ISSUE TITLE
Adjust shuttle location

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Offbot_Code#120]

**Comment by TaylerUva** [comment]
@ACat701 due to dev time we should probably not make this pose based, just a set point (like it is currently. If pose is super broken for some reason it will be nice to have this as a fall back. Lets still update the drop point to what we talked about though

**Comment by alicekuznetsov** [comment]
I dont think the dev time would be much longer considering its just PrepVision with a different interpolation tree, so I dont want to completely throw away the idea, but Im fine with adjusting the preset for now and potentially revisiting it later
