### ISSUE TITLE
Determine Sensor type for the Shooter

### ISSUE THREAD

**Issue by alicekuznetsov** [FRCTeam3255/2024_Offbot_Code#13]
Color sensor? Beam Break? Something else? The world may never know.
(Well, it will know when this issue is closed, but we need drama here!)

Write baseline functionality for our beam break sensors and see how they function. From there, determine if we should use them or order something else

**Comment by TaylerUva** [comment]
![](https://m.media-amazon.com/images/I/51+vmkw5IeL.jpg)

<img width="366" alt="image" src="https://github.com/user-attachments/assets/c4e9aee0-a22e-41a7-aae3-a02b0457f5a9">
