### ISSUE TITLE
Critical Firmware v1.2.5 update for the radio

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Offbot_Code#134]
We must do it ASAP for both radios
<https://www.chiefdelphi.com/t/vh-109-vh-113-firmware-v1-2-5-critical-update/474358|https://www.chiefdelphi.com/t/vh-109-vh-113-firmware-v1-2-5-critical-update/474358>

**Comment by AlenaNguyen** [comment]
the deed is done
