### ISSUE TITLE
Update Radio firmware

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Offbot_Code#62]
https://www.chiefdelphi.com/t/vivid-hosting-vh-109-1-2-0-firmware-release/471258/5

We can now name radios

**Comment by TaylerUva** [comment]
This is now mandatory per BaB @ACat701 and @Alenguye582

**Comment by alicekuznetsov** [comment]
@Alenguye582  could you do this on tuesday while I'm gone? maybe swap to the Rio2 then too if that's possible. I want to have data on if the rio2 actually works, which it should, but anything is possible man

**Comment by AlenaNguyen** [comment]
> @Alenguye582 could you do this on tuesday while I'm gone? maybe swap to the Rio2 then too if that's possible. I want to have data on if the rio2 actually works, which it should, but anything is possible man

I don't think I can, I'm getting senior portraits done today 😿
