### ISSUE TITLE
Create State Machine

### ISSUE THREAD

**Issue by BrodyKarr** [FRCTeam3255/2024_Offbot_Code#7]
possible states;
- Intake
- store in transfer
- store in elevator
- climb
- trap
- shuffle
- amp
- speaker

**Comment by TaylerUva** [comment]
![image](https://github.com/user-attachments/assets/a3245fc1-ff21-4c45-98aa-3ae0770b6815)

**Comment by alicekuznetsov** [comment]
https://www.tldraw.com/ro/DX06u039erL_iV6q0ARSn?v=-1560,-1096,5776,2777&p=page
✨✨✨✨

can someone contact admin to get tldraw unbanned from the wifi pleaseeee🥺🥺🥺🥺🥺🥺🥺

**Comment by TaylerUva** [comment]
We need to add a `Prep Shoot Backwards` state @ACat701 @Alenguye582

**Comment by alicekuznetsov** [comment]
I was initially thinking of integrating that functionality into just prep speaker- we could have a separate state if that makes more sense though

**Comment by TaylerUva** [comment]
> I was initially thinking of integrating that functionality into just prep speaker- we could have a separate state if that makes more sense though

It is sounding like mechanically this state is more similar to `Prep Amp` (a single set position with no variability). `Prep Speaker` is suppose to dynamically set the pivot based on pose so I am thinking they should be separate.

**Comment by AlenaNguyen** [comment]
> It is sounding like mechanically this state is more similar to `Prep Amp` (a single set position with no variability). 

Oh, so Prep Backwards is kinda just a preset for shooting at one spot (like the subwoofer)?
