### ISSUE TITLE
Zeroing in Auto causes auto to only work once per deploy

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Offbot_Code#94]

**Comment by alicekuznetsov** [comment]
Consulted my programming council and it appears that we're having the same issue mentioned [here](https://github.com/Patribots4738/Crescendo2024/discussions/180#discussioncomment-8564078)- feel free to take a read yourself, but the gist of it is that our error is stemming from WPILib trying to reference a command that has already been run, so we need to re-register the command every time we try to run it. Let me know what you think :]

@TaylerUva

**Comment by TaylerUva** [comment]
That was what I figured was happening. Perhaps wrapping in a method and adding a 'new' would fix it.
